### ISSUE TITLE
Add command line argument for passing Google Cloud Credentials JSON

### ISSUE THREAD

**Issue by hongkongkiwi** [ericnorris/google-kms-x509#4]
I would like to pass the JSON credentials file for the service account via a command line argument, is it possible to add this feature?

**Comment by ericnorris** [comment]
@hongkongkiwi is it not possible to set the `GOOGLE_APPLICATION_CREDENTIALS` environment variable? As far as I can tell that should just work, along with anything else listed in https://cloud.google.com/docs/authentication/production#automatically.

**Comment by ericnorris** [comment]
Closing this issue, feel free to reopen if this is actually a problem.
