### ISSUE TITLE
Plugin Interface for other providers? (AWS, Azure, SmallStep etc)

### ISSUE THREAD

**Issue by hongkongkiwi** [ericnorris/google-kms-x509#6]
This is a really great tool.

I was wondering if it was possible to abstract out the provider as a plugin so others can add support for AWS KMS or Azure alternatives.

Specifically I'm after support for AWS KMS and havn't found a similar tool to support that so was hoping to create a plugin.

**Comment by ericnorris** [comment]
Hey! Glad you like it. While I'm not completely opposed to this, I also like the the idea of this being a small single-purpose binary. I'm going to close this issue for now, but I've labeled it as an enhancement in case I change my mind.
